package com.duggan.workflow.shared.model;

/**
 * This is a set of notifications that will be supported
 * by this application
 * 
 * It does not include any notifications generated by the 
 * JBPM engine for task escalation
 * 
 * @author duggan
 *
 */
public enum NotificationType {

	APPROVALREQUEST_APPROVERNOTE("Invoice INV/001/2013 - Request for approval from Calcacuervo. (2 mins ago)"),//for approver
	APPROVALREQUEST_OWNERNOTE("Invoice INV/001/2013 - succesfully submitted for approval (10 seconds ago)"),//for ownere - request assigned
	TASKCOMPLETED_APPROVERNOTE("Invoice INV/001/2013 has been approved/denied. (requested by calcacuervo) (20mins ago)"),//for approver
	TASKCOMPLETED_OWNERNOTE("Invoice INV/001/2013 - Denied by mariano (1hr ago)"),//for owner
	COMMENT("INV/001/2013 - Andrew commented on this document  (5 hrs ago)"),
	TASK_REMINDER("Reminder re: Document INV/001/2013"),
	PROCESS_COMPLETED("Invoice INV/001/2013 approval process completed (3 mins ago)");
	
	String notificationTemplate;//example template - To be removed later
	
	private NotificationType(String template){
		this.notificationTemplate=template;
	}
	
}
