package com.duggan.workflow.shared.model;

/**
 * This is a set of notifications that will be supported
 * by this application
 * 
 * It does not include any notifications generated by the 
 * JBPM engine for task escalation
 * 
 * @author duggan
 *
 */
public enum NotificationType {

	APPROVALREQUEST_APPROVERNOTE,//for approver
	APPOVALREQUEST_OWNERNOTE,//for ownere - request assigned
	TASKCOMPLETED_APPROVERNOTE,//for approver
	TASKCOMPLETED_OWNERNOTE,//for owner
	COMMENT,
	TASK_REMINDER,
	PROCESS_COMPLETED;
	
	
}
