package com.duggan.workflow.shared.model;

/**
 * This is a set of notifications that will be supported
 * by this application
 * 
 * It does not include any notifications generated by the 
 * JBPM engine for task escalation
 * 
 * @author duggan
 *
 */
public enum NotificationType {

	APPROVAL_REQUEST,
	TASKCOMPLETED_APPROVED,
	TASKCOMPLETED_DENIED,
	COMMENT,
	TASK_REMINDER
	
	
}
